name: Test launcher

on:
  workflow_dispatch:
    inputs:
      test-area:
        description: 'Test area (e.g. rq or Positive, Create or Update; if missing, all tests will be running)'
        required: true
        default: petstore_delete_tests
        type: choice
        options:
          - CRUD
          - petstore_positive
          - petstore_negative
          - petstore_create_tests
          - petstore_read_tests
          - petstore_update_tests
          - petstore_delete_tests

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_IN_PROJECT: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11.2"
      - name: Install poetry
        uses: dschep/install-poetry-action@v1.3

      - name: Configure poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project false
          poetry config cache-dir ~/.poetry
          poetry config virtualenvs.path ~/.poetry/venv
        
      - name: Run tests
        run: pytest -m ${{ github.event.inputs.test-area }}
