name: Test launcher

on:
  workflow_dispatch:
    inputs:
      test-area:
        description: 'Test area (e.g. rq or Positive, Create or Update; if missing, all tests will be running)'
        required: true
        default: CRUD
        type: choice
        options:
          - CRUD
          - Positive
          - Negative
          - petstore_create_tests
          - Read
          - Update
          - Delete

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_IN_PROJECT: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11.2"
      - name: Install poetry
        run: |
          pip install poetry==1.4.2
          poetry self update
      - name: Install pytest
        run: poetry run pip install pytest
      - name: Add pytest to PATH
        run: |
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> $HOME/.bashrc
          source $HOME/.bashrc
      - name: cache venv
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install
      - name: Activate virtual environment
        run: source .venv/bin/activate
        
      - name: Run tests
        run: /home/runner/work/bin/pytest -m ${{ github.event.inputs.test-area }}
